version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    ports: ['5432:5432']   # expose on localhost for development

  migrate:
    image: postgres:16
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
    volumes:
      - ./scripts/auto-migrate.sh:/auto-migrate.sh:ro
      - ./scripts/migrations:/migrations:ro
    command: ["/bin/sh", "/auto-migrate.sh"]
    restart: "no"

volumes:
  dbdata:
