import type { Item } from './items.js';

/**
 * Starter equipment templates (shield, armor pieces, jewelry). Kept in a
 * separate file from the legacy ITEMS map so packages/content/items.ts stays
 * under the maintainability gate while we land the L2-style equipment system.
 */
export const EQUIPMENT_STARTER_ITEMS: Record<string, Item> = {
  wooden_shield: {
    id: 'wooden_shield',
    name: 'Wooden Shield',
    description: 'A round wooden shield rimmed with iron.',
    icon: 'wooden_shield.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 5,
    kind: 'shield',
    grade: 'none',
    weight: 1800,
    equip: { bodyPart: 'shield', allowedSlots: ['OFF_HAND'], handUsage: 'shield' },
    stats: { pDef: 5 },
  },
  leather_helmet: {
    id: 'leather_helmet',
    name: 'Leather Helmet',
    description: 'Padded leather cap that takes the edge off a blow.',
    icon: 'leather_helmet.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 3,
    kind: 'armor',
    grade: 'none',
    weight: 900,
    equip: { bodyPart: 'head', allowedSlots: ['HEAD'], armorType: 'light' },
    stats: { pDef: 3 },
    setId: 'leather_set',
  },
  leather_tunic: {
    id: 'leather_tunic',
    name: 'Leather Tunic',
    description: 'Stitched leather covering the chest.',
    icon: 'leather_tunic.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 8,
    kind: 'armor',
    grade: 'none',
    weight: 2200,
    equip: { bodyPart: 'chest', allowedSlots: ['CHEST'], armorType: 'light' },
    stats: { pDef: 8 },
    setId: 'leather_set',
  },
  leather_pants: {
    id: 'leather_pants',
    name: 'Leather Pants',
    description: 'Reinforced leather leggings.',
    icon: 'leather_pants.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 6,
    kind: 'armor',
    grade: 'none',
    weight: 1800,
    equip: { bodyPart: 'legs', allowedSlots: ['LEGS'], armorType: 'light' },
    stats: { pDef: 6 },
    setId: 'leather_set',
  },
  leather_gloves: {
    id: 'leather_gloves',
    name: 'Leather Gloves',
    description: 'Worn leather gloves with iron knuckles.',
    icon: 'leather_gloves.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 2,
    kind: 'armor',
    grade: 'none',
    weight: 500,
    equip: { bodyPart: 'gloves', allowedSlots: ['GLOVES'], armorType: 'light' },
    stats: { pDef: 2 },
    setId: 'leather_set',
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    description: 'Sturdy boots for long marches.',
    icon: 'leather_boots.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 2,
    kind: 'armor',
    grade: 'none',
    weight: 700,
    equip: { bodyPart: 'boots', allowedSlots: ['BOOTS'], armorType: 'light' },
    stats: { pDef: 2 },
    setId: 'leather_set',
  },
  plate_cuirass: {
    id: 'plate_cuirass',
    name: 'Plate Cuirass',
    description: 'Full-body plate that covers chest and legs together.',
    icon: 'plate_cuirass.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 20,
    kind: 'armor',
    grade: 'c',
    weight: 6500,
    equip: { bodyPart: 'fullBody', allowedSlots: ['CHEST', 'LEGS'], armorType: 'heavy' },
    stats: { pDef: 20 },
  },
  bone_necklace: {
    id: 'bone_necklace',
    name: 'Bone Necklace',
    description: 'A simple necklace of polished bone.',
    icon: 'bone_necklace.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 0,
    kind: 'jewelry',
    grade: 'none',
    weight: 300,
    equip: { bodyPart: 'neck', allowedSlots: ['NECK'] },
    stats: { mDef: 4 },
  },
  bone_earring: {
    id: 'bone_earring',
    name: 'Bone Earring',
    description: 'A pair of light bone earrings.',
    icon: 'bone_earring.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 0,
    kind: 'jewelry',
    grade: 'none',
    weight: 100,
    equip: { bodyPart: 'earring', allowedSlots: ['EAR_LEFT', 'EAR_RIGHT'] },
    stats: { mDef: 2 },
  },
  bone_ring: {
    id: 'bone_ring',
    name: 'Bone Ring',
    description: 'A bone band carved with simple runes.',
    icon: 'bone_ring.svg',
    stackable: false,
    type: 'armor',
    defenseValue: 0,
    kind: 'jewelry',
    grade: 'none',
    weight: 100,
    equip: { bodyPart: 'ring', allowedSlots: ['RING_LEFT', 'RING_RIGHT'] },
    stats: { mDef: 2 },
  },
  short_bow: {
    id: 'short_bow',
    name: 'Short Bow',
    description: 'A simple wooden bow strung with hemp. Light enough for any ranger.',
    icon: 'short_bow.svg',
    stackable: false,
    type: 'weapon',
    attackPower: 6,
    kind: 'weapon',
    grade: 'none',
    weight: 1200,
    // Bow uses the 'bow' hand-usage so the equip transaction
    // atomically frees the off-hand (a shield can't coexist with a
    // drawn bow).
    equip: { bodyPart: 'mainHand', allowedSlots: ['MAIN_HAND'], handUsage: 'bow', weaponType: 'bow' },
    stats: { pAtk: 6 },
  },
};
