import type { SkillDef, SkillId } from './skills.js';

export const ROTATION_BATCH_SKILLS: Partial<Record<SkillId, SkillDef>> = {
  ember_relay: {
    id: 'ember_relay', name: 'Ember Relay',
    description: 'Kick an active burn through nearby enemies; a burning primary target turns the relay into a faster combo window.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical', damageElement: 'fire',
    manaCost: 44, castMs: 450, cooldownMs: 21000, dmg: 165, range: 20, area: 6,
    levelRequired: 20, requiresTarget: true,
    role: 'damage', school: 'fire', scalingStat: 'int', targetMode: 'enemy', pveUse: ['finisher', 'pack'],
    customBehavior: 'emberRelay', effects: [],
  },
  seismic_rend: {
    id: 'seismic_rend', name: 'Seismic Rend',
    description: 'Split the ground under a bleeding foe, pulling the pack inward and stunning enemies already opened by wounds.',
    icon: '/game/skills/skill_melee.svg', cat: 'aura', kind: 'physical',
    manaCost: 34, castMs: 250, cooldownMs: 19000, dmg: 150, range: 7, area: 5.25,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'physical', scalingStat: 'str', targetMode: 'enemy', pveUse: ['finisher', 'pack'],
    customBehavior: 'seismicRend', effects: [],
  },
  harmonic_seal: {
    id: 'harmonic_seal', name: 'Harmonic Seal',
    description: 'Draw a holy seal that links two enemies while shielding allies standing inside the resonance.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility', damageElement: 'holy',
    manaCost: 46, castMs: 650, cooldownMs: 24000, dmg: 95, range: 18, area: 5.5,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'holy', scalingStat: 'men', targetMode: 'enemy', pveUse: ['pack', 'sustain'],
    customBehavior: 'harmonicSeal', effects: [],
  },
  nightfall_net: {
    id: 'nightfall_net', name: 'Nightfall Net',
    description: 'Pin a marked quarry under a shadow net, leaving a decoy at the edge of the trap while poison spreads.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical', damageElement: 'shadow',
    manaCost: 36, castMs: 250, cooldownMs: 20000, dmg: 135, range: 22, area: 4.5,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'shadow', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'escape', 'pack'],
    customBehavior: 'nightfallNet', effects: [],
  },
  pain_dividend: {
    id: 'pain_dividend', name: 'Pain Dividend',
    description: 'Cash out a taunted enemy into a reflection ward, splashing pain through enemies focused on you.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical', damageElement: 'shadow',
    manaCost: 40, castMs: 0, cooldownMs: 23000, dmg: 130, range: 12, area: 5,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'tank', school: 'shadow', scalingStat: 'con', targetMode: 'enemy', pveUse: ['sustain', 'boss', 'pack'],
    customBehavior: 'painDividend', effects: [],
  },
  cinder_halo: {
    id: 'cinder_halo', name: 'Cinder Halo',
    description: 'Ignite a defensive halo: allies are shielded while nearby enemies burn harder if you were already warded.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility', damageElement: 'holy',
    manaCost: 42, castMs: 300, cooldownMs: 22000, dmg: 95, area: 5.75,
    levelRequired: 20, selfTarget: true,
    role: 'tank', school: 'holy', scalingStat: 'men', targetMode: 'area-self', pveUse: ['sustain', 'pack'],
    customBehavior: 'cinderHalo', effects: [],
  },
  loaded_mirage: {
    id: 'loaded_mirage', name: 'Loaded Mirage',
    description: 'Throw false coin-shadows around the target; marked victims are rooted while decoys draw the eye.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 34, castMs: 0, cooldownMs: 21000, dmg: 120, range: 13, area: 4.25,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'control', school: 'physical', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'pack', 'sustain'],
    customBehavior: 'loadedMirage', effects: [],
  },
};
