import type { SkillDef, SkillId } from './skills.js';

/**
 * Spec + proficiency skill catalog, split out from skills.ts to keep
 * that file under the 700-line maintainability gate. Spread into
 * SKILLS in skills.ts. Each id is referenced by exactly one
 * SPECIALIZATIONS[*].specSkills or .proficiencySkills entry; the
 * engine gate (canPlayerLearnSkill + classifyLearnRejection) reads
 * SPECIALIZATIONS to decide eligibility — there is no per-skill
 * code branch.
 */
export const SPEC_AND_PROFICIENCY_SKILLS: Partial<Record<SkillId, SkillDef>> = {
  // ---- Spec skills (Lv 20 unlock) ----
  arcane_blast: {
    id: 'arcane_blast', name: 'Arcane Blast',
    description: 'Concentrated arcane bolt; long range, hits hard.',
    icon: '/game/skills/skill_fireball.png', cat: 'projectile', kind: 'magical',
    manaCost: 35, castMs: 900, cooldownMs: 6000, dmg: 240, range: 24,
    levelRequired: 20, requiresTarget: true,
    effects: [{ type: 'damage', value: 240 }],
  },
  phase_prison: {
    id: 'phase_prison', name: 'Phase Prison',
    description: 'Fold space around a target, dragging nearby enemies into a rooted silence while charging your next arcane cast.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical',
    damageElement: 'arcane',
    manaCost: 48, castMs: 500, cooldownMs: 24000, dmg: 120, range: 20, area: 4.75,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'arcane', scalingStat: 'int', targetMode: 'enemy', pveUse: ['pack', 'opener'],
    customBehavior: 'phasePrison',
    effects: [],
  },
  meteor: {
    id: 'meteor', name: 'Meteor',
    description: 'Calls a meteor from the sky, burning the area.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical',
    damageElement: 'fire',
    manaCost: 55, castMs: 1400, cooldownMs: 15000, dmg: 320, range: 18, area: 4,
    levelRequired: 20, requiresTarget: false,
    effects: [{ type: 'damage', value: 320 }, { type: 'burn', value: 4, durationMs: 6000 }],
  },
  magma_chain: {
    id: 'magma_chain', name: 'Magma Chain',
    description: 'Hook a burning chain into an enemy, yanking them toward you and leaving them scorched.',
    icon: '/game/skills/skill_fireball.png', cat: 'instant', kind: 'magical',
    damageElement: 'fire',
    manaCost: 42, castMs: 300, cooldownMs: 18000, dmg: 150, range: 18,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'fire', scalingStat: 'int', targetMode: 'enemy', pveUse: ['opener', 'single-target', 'escape'],
    customBehavior: 'magmaChain',
    effects: [],
  },
  combustion_bloom: {
    id: 'combustion_bloom', name: 'Combustion Bloom',
    description: 'Detonate Burn on a target into an explosive flower of flame; a burning target makes the bloom wider and empowers you.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical',
    damageElement: 'fire',
    manaCost: 46, castMs: 550, cooldownMs: 22000, dmg: 175, range: 19, area: 5,
    levelRequired: 20, requiresTarget: true,
    role: 'damage', school: 'fire', scalingStat: 'int', targetMode: 'enemy', pveUse: ['pack', 'boss'],
    customBehavior: 'combustionBloom',
    effects: [],
  },
  rage: {
    id: 'rage', name: 'Rage',
    description: 'Surge of fury: hit harder for a short window.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'utility',
    manaCost: 20, castMs: 0, cooldownMs: 30000, levelRequired: 20, isBlocking: false,
    effects: [{ type: 'bless', value: 25, durationMs: 10000 }],
  },
  blood_magnet: {
    id: 'blood_magnet', name: 'Blood Magnet',
    description: 'Drag nearby enemies into melee range, opening bleeding wounds while each victim feeds a short attack-speed surge.',
    icon: '/game/skills/skill_melee.svg', cat: 'aura', kind: 'physical',
    manaCost: 36, castMs: 0, cooldownMs: 24000, dmg: 85, area: 7,
    levelRequired: 20, isBlocking: false, selfTarget: true,
    role: 'control', school: 'physical', scalingStat: 'str', targetMode: 'area-self', pveUse: ['pack', 'opener', 'sustain'],
    customBehavior: 'bloodMagnet',
    effects: [],
  },
  execute: {
    id: 'execute', name: 'Execute',
    description: 'Finishing blow against a wounded target.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 25, castMs: 400, cooldownMs: 8000, dmg: 280, range: 4,
    levelRequired: 20, requiresTarget: true,
    // B9 — up to +150% damage as the target's HP drops to 0.
    offense: { executeBonus: 1.5 },
    effects: [{ type: 'damage', value: 280 }],
  },
  duelist_lunge: {
    id: 'duelist_lunge', name: 'Duelist Lunge',
    description: 'Dash through the target and cut so sharply the closest second foe is nicked by the same line.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 32, castMs: 0, cooldownMs: 15000, dmg: 210, range: 11,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'damage', school: 'physical', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'single-target'],
    customBehavior: 'duelistLunge',
    effects: [],
  },
  greater_heal: {
    id: 'greater_heal', name: 'Greater Heal',
    description: 'A potent restoration spell.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 40, castMs: 1500, cooldownMs: 8000, levelRequired: 20,
    effects: [{ type: 'heal', value: 220 }],
  },
  lifeline_swap: {
    id: 'lifeline_swap', name: 'Lifeline Swap',
    description: 'Trade places with a wounded ally, pulling them out of danger while shielding both of you.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 52, castMs: 250, cooldownMs: 28000, range: 16,
    levelRequired: 20, requiresTarget: true,
    role: 'heal', school: 'holy', scalingStat: 'men', targetMode: 'ally', pveUse: ['sustain', 'escape'],
    customBehavior: 'lifelineSwap',
    effects: [],
  },
  empower: {
    id: 'empower', name: 'Empower',
    description: 'Stack a damage-boost buff on the caster.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 30, castMs: 600, cooldownMs: 20000, levelRequired: 20,
    effects: [{ type: 'bless', value: 20, durationMs: 12000 }],
  },
  echoing_benediction: {
    id: 'echoing_benediction', name: 'Echoing Benediction',
    description: 'A chain prayer jumps through the most wounded nearby allies, healing, shielding, and blessing the first target it reaches.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 48, castMs: 600, cooldownMs: 26000, area: 9,
    levelRequired: 20, selfTarget: true,
    role: 'heal', school: 'holy', scalingStat: 'men', targetMode: 'area-self', pveUse: ['sustain', 'boss'],
    customBehavior: 'echoingBenediction',
    effects: [],
  },
  snipe: {
    id: 'snipe', name: 'Snipe',
    description: 'A precise long-range arrow shot.',
    icon: '/game/skills/skill_melee.svg', cat: 'projectile', kind: 'physical',
    manaCost: 25, castMs: 1100, cooldownMs: 9000, dmg: 280, range: 32,
    levelRequired: 20, requiresTarget: true,
    effects: [{ type: 'damage', value: 280 }],
  },
  tripwire_volley: {
    id: 'tripwire_volley', name: 'Tripwire Volley',
    description: 'Pin the primary target with a hidden wire while the same shot knocks nearby enemies off the line.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 34, castMs: 350, cooldownMs: 18000, dmg: 190, range: 24, area: 4.5,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'physical', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['pack', 'opener'],
    customBehavior: 'tripwireVolley',
    effects: [],
  },
  silent_step: {
    id: 'silent_step', name: 'Silent Step',
    description: 'Brief invisibility for repositioning.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'utility',
    manaCost: 30, castMs: 0, cooldownMs: 45000, levelRequired: 20, isBlocking: false,
    // selfTarget so the stealth/aggroReset always land on the caster, never
    // a targeted enemy (matches Vanish; guards the with-target cast path).
    selfTarget: true,
    // C16 — drop current chasers too, so the invisibility actually lets
    // you reposition (invisible alone doesn't clear existing threat).
    effects: [{ type: 'invisible', value: 1, durationMs: 8000 }, { type: 'aggroReset', value: 1 }],
  },
  umbra_mine: {
    id: 'umbra_mine', name: 'Umbra Mine',
    description: 'Plant a shadow mine under an enemy, spawning a decoy while nearby foes are rooted, poisoned, and marked.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    damageElement: 'shadow',
    manaCost: 38, castMs: 300, cooldownMs: 23000, dmg: 115, range: 21, area: 4.25,
    levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'shadow', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['pack', 'escape'],
    customBehavior: 'umbraMine',
    effects: [],
  },
  holy_shield: {
    id: 'holy_shield', name: 'Holy Shield',
    description: 'A radiant ward that absorbs damage.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 35, castMs: 500, cooldownMs: 25000, levelRequired: 20,
    effects: [{ type: 'shield', value: 250, durationMs: 12000 }],
  },
  guardian_hook: {
    id: 'guardian_hook', name: 'Guardian Hook',
    description: 'Hook an enemy into your guard, taunting nearby foes and raising a shield before they crash in.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'physical',
    manaCost: 38, castMs: 0, cooldownMs: 21000, dmg: 130, range: 15, area: 5.5,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'tank', school: 'physical', scalingStat: 'con', targetMode: 'enemy', pveUse: ['opener', 'pack'],
    customBehavior: 'guardianHook',
    effects: [],
  },
  vengeance_tether: {
    id: 'vengeance_tether', name: 'Vengeance Tether',
    description: 'Bind a foe to your guard with a shadow chain, forcing pursuit while your reflection ward punishes incoming blows.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'magical',
    damageElement: 'shadow',
    manaCost: 42, castMs: 300, cooldownMs: 26000, dmg: 150, range: 15,
    levelRequired: 20, requiresTarget: true,
    role: 'tank', school: 'shadow', scalingStat: 'con', targetMode: 'enemy', pveUse: ['boss', 'sustain'],
    customBehavior: 'vengeanceTether',
    effects: [],
  },
  shadow_strike: {
    id: 'shadow_strike', name: 'Shadow Strike',
    description: 'Blink through the target and strike from the far side, bypassing normal defenses.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 25, castMs: 500, cooldownMs: 10000, dmg: 240, range: 4,
    levelRequired: 20, requiresTarget: true,
    blink: { offset: 1.5 },
    // B12 — ignores up to 500 P.Def/M.Def (most armor).
    offense: { armorPen: 500 },
    effects: [{ type: 'damage', value: 240 }],
  },
  phoenix_ward: {
    id: 'phoenix_ward', name: 'Phoenix Ward',
    description: 'Flame-laced shield that absorbs damage.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 35, castMs: 600, cooldownMs: 30000, levelRequired: 20,
    effects: [{ type: 'shield', value: 280, durationMs: 14000 }],
  },
  phoenix_leap: {
    id: 'phoenix_leap', name: 'Phoenix Leap',
    description: 'Leap through a foe in a burst of holy fire, shielding yourself as nearby enemies ignite.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'magical',
    damageElement: 'holy',
    manaCost: 44, castMs: 0, cooldownMs: 22000, dmg: 180, range: 14, area: 3.5,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'holy', scalingStat: 'str', targetMode: 'enemy', pveUse: ['opener', 'sustain', 'pack'],
    customBehavior: 'phoenixLeap',
    effects: [],
  },
  sunbreak_charge: {
    id: 'sunbreak_charge', name: 'Sunbreak Charge',
    description: 'Charge through a foe in a lance of holy fire, burning enemies at the landing point while nearby allies are restored.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'magical',
    damageElement: 'holy',
    manaCost: 46, castMs: 0, cooldownMs: 25000, dmg: 170, range: 15, area: 4.5,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'holy', scalingStat: 'str', targetMode: 'enemy', pveUse: ['opener', 'pack', 'sustain'],
    customBehavior: 'sunbreakCharge',
    effects: [],
  },
  sacred_pulse: {
    id: 'sacred_pulse', name: 'Sacred Pulse',
    description: 'A burst of radiance that heals nearby allies.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 40, castMs: 800, cooldownMs: 18000, area: 6, levelRequired: 20,
    effects: [{ type: 'heal', value: 160 }],
  },
  aegis_relay: {
    id: 'aegis_relay', name: 'Aegis Relay',
    description: 'Call nearby allies inward, refreshing their footing with a shared shield and heal.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 46, castMs: 400, cooldownMs: 26000, area: 7, levelRequired: 20, selfTarget: true,
    role: 'utility', school: 'holy', scalingStat: 'men', targetMode: 'area-self', pveUse: ['sustain', 'escape'],
    customBehavior: 'aegisRelay',
    effects: [],
  },
  tidal_barrier: {
    id: 'tidal_barrier', name: 'Tidal Barrier',
    description: 'Release a cleansing wave that pushes enemies away while nearby allies receive a shield and stronger healing if debuffs are washed off.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 50, castMs: 450, cooldownMs: 27000, area: 6,
    levelRequired: 20, selfTarget: true,
    role: 'utility', school: 'holy', scalingStat: 'men', targetMode: 'area-self', pveUse: ['sustain', 'escape', 'pack'],
    customBehavior: 'tidalBarrier',
    effects: [],
  },
  lucky_strike: {
    id: 'lucky_strike', name: 'Lucky Strike',
    description: 'A precise attack with a chance to crit big.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 22, castMs: 300, cooldownMs: 12000, dmg: 220, range: 4,
    levelRequired: 20, requiresTarget: true,
    // B10 — +50% crit chance and a bigger crit on this hit.
    offense: { bonusCritChance: 0.5, bonusCritMult: 0.5 },
    effects: [{ type: 'damage', value: 220 }],
  },
  jackpot_snare: {
    id: 'jackpot_snare', name: 'Jackpot Snare',
    description: 'Snap a lucky snare onto the target, marking the pack and sharpening your loot sense for the next opening.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 32, castMs: 250, cooldownMs: 21000, dmg: 145, range: 14, area: 3.75,
    levelRequired: 20, requiresTarget: true,
    role: 'utility', school: 'physical', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'pack'],
    customBehavior: 'jackpotSnare',
    effects: [],
  },
  wind_dash: {
    id: 'wind_dash', name: 'Wind Dash',
    description: 'A burst of speed that breaks pursuit.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'utility',
    manaCost: 18, castMs: 0, cooldownMs: 20000, levelRequired: 20, isBlocking: false,
    // §SKILL-ENGINE B7 — actually a speed burst that drops chasers
    // (was an `evasion` dodge buff, unrelated to its text).
    effects: [{ type: 'speed_boost', value: 40, durationMs: 6000 }, { type: 'aggroReset', value: 1 }],
  },
  razorwind_step: {
    id: 'razorwind_step', name: 'Razorwind Step',
    description: 'Step through a poisoned foe and leave slicing wind in your wake; poisoned targets make the cuts spread poison onward.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    damageElement: 'poison',
    manaCost: 34, castMs: 0, cooldownMs: 18000, dmg: 125, range: 13, area: 3.75,
    levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'physical', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'escape', 'single-target'],
    customBehavior: 'razorwindStep',
    effects: [],
  },
  // ---- Proficiency skills (Lv 40 unlock) ----
  arcane_supremacy: {
    id: 'arcane_supremacy', name: 'Arcane Supremacy',
    description: 'Devastating spell that spends banked Arcane Charges for overflow burst.',
    icon: '/game/skills/skill_fireball.png', cat: 'projectile', kind: 'magical',
    manaCost: 80, castMs: 1800, cooldownMs: 25000, dmg: 520, range: 28,
    levelRequired: 40, requiresTarget: true,
    effects: [{ type: 'damage', value: 520 }],
  },
  time_sphere: {
    id: 'time_sphere', name: 'Time Sphere',
    description: 'Collapse time into a broad dome around the target: every combatant caught inside is stopped, except the caster.',
    icon: '/game/skills/skill-icon-arcane-supremacy.png', cat: 'aura', kind: 'utility',
    manaCost: 75, castMs: 700, cooldownMs: 45000, range: 20, area: 8,
    levelRequired: 40, requiresTarget: true,
    role: 'control', school: 'arcane', scalingStat: 'int', targetMode: 'enemy', pveUse: ['pack', 'opener'],
    shape: { kind: 'circle', radius: 8, anchor: 'target' },
    affects: 'all',
    effects: [{ type: 'timeStop', value: 1, durationMs: 3500 }],
  },
  dimensional_swap: {
    id: 'dimensional_swap', name: 'Dimensional Swap',
    description: 'Tear open a rift and trade places with the enemy, disorienting them on arrival.',
    icon: '/game/skills/skill-icon-arcane-supremacy.png', cat: 'instant', kind: 'magical',
    damageElement: 'arcane',
    manaCost: 55, castMs: 0, cooldownMs: 26000, dmg: 180, range: 18,
    levelRequired: 40, requiresTarget: true, isBlocking: false,
    role: 'control', school: 'arcane', scalingStat: 'int', targetMode: 'enemy', pveUse: ['single-target', 'escape'],
    swap: {},
    effects: [{ type: 'damage', value: 180 }, { type: 'stun', value: 1, durationMs: 900 }],
  },
  inferno_aura: {
    id: 'inferno_aura', name: 'Inferno Aura',
    description: 'A roaring fire surrounds you, burning everything near.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical',
    damageElement: 'fire',
    manaCost: 60, castMs: 800, cooldownMs: 30000, area: 5, levelRequired: 40,
    effects: [{ type: 'burn', value: 6, durationMs: 12000 }],
  },
  blood_frenzy: {
    id: 'blood_frenzy', name: 'Blood Frenzy',
    description: 'Push your body past the limit; massive damage spike.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'utility',
    manaCost: 30, castMs: 0, cooldownMs: 60000, levelRequired: 40, isBlocking: false,
    effects: [{ type: 'bless', value: 50, durationMs: 12000 }],
  },
  killing_strike: {
    id: 'killing_strike', name: 'Killing Strike',
    description: 'A perfect finishing blow.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 40, castMs: 500, cooldownMs: 18000, dmg: 520, range: 4,
    levelRequired: 40, requiresTarget: true,
    effects: [{ type: 'damage', value: 520 }],
  },
  mass_heal: {
    id: 'mass_heal', name: 'Mass Heal',
    description: 'Restore HP to everyone around you.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 70, castMs: 1500, cooldownMs: 25000, area: 8, levelRequired: 40,
    effects: [{ type: 'heal', value: 280 }],
  },
  group_bless: {
    id: 'group_bless', name: 'Group Bless',
    description: 'Stronger, longer bless that radiates to allies.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 60, castMs: 1200, cooldownMs: 40000, area: 8, levelRequired: 40,
    effects: [{ type: 'bless', value: 35, durationMs: 20000 }],
  },
  waygate: {
    id: 'waygate', name: 'Waygate',
    description: 'Open a short-lived gate for nearby allies, granting a burst of speed and dropping pursuit.',
    icon: '/game/skills/skill-icon-group-bless.png', cat: 'aura', kind: 'utility',
    manaCost: 55, castMs: 500, cooldownMs: 45000, area: 7, levelRequired: 40,
    role: 'mobility', school: 'arcane', scalingStat: 'wit', targetMode: 'area-self', pveUse: ['escape', 'sustain'],
    effects: [{ type: 'speed_boost', value: 55, durationMs: 5000 }, { type: 'aggroReset', value: 1 }],
  },
  aimed_volley: {
    id: 'aimed_volley', name: 'Aimed Volley',
    description: 'A perfectly placed barrage of arrows that cashes out Marked targets.',
    icon: '/game/skills/skill_melee.svg', cat: 'projectile', kind: 'physical',
    manaCost: 55, castMs: 1500, cooldownMs: 25000, dmg: 380, range: 30, area: 4,
    levelRequired: 40, requiresTarget: false,
    effects: [{ type: 'damage', value: 380 }],
  },
  shadow_arrow: {
    id: 'shadow_arrow', name: 'Shadow Arrow',
    description: 'A piercing dark arrow that ignores most defenses.',
    icon: '/game/skills/skill_melee.svg', cat: 'projectile', kind: 'physical',
    manaCost: 45, castMs: 800, cooldownMs: 12000, dmg: 360, range: 28,
    levelRequired: 40, requiresTarget: true,
    // B12 — ignores up to 500 P.Def/M.Def (most armor).
    offense: { armorPen: 500 },
    effects: [{ type: 'damage', value: 360 }],
  },
  divine_taunt: {
    id: 'divine_taunt', name: 'Divine Taunt',
    description: 'Compel every enemy nearby to attack you.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 50, castMs: 0, cooldownMs: 30000, area: 6, levelRequired: 40, isBlocking: false,
    effects: [{ type: 'taunt', value: 1, durationMs: 8000 }],
  },
  soul_eater: {
    id: 'soul_eater', name: 'Soul Eater',
    description: 'Drain life from your target.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'magical',
    manaCost: 50, castMs: 600, cooldownMs: 15000, dmg: 280, range: 8,
    levelRequired: 40, requiresTarget: true,
    // B11 — heals the caster for 50% of the damage dealt.
    offense: { lifestealPct: 0.5 },
    effects: [{ type: 'damage', value: 280 }],
  },
  spectral_guard: {
    id: 'spectral_guard', name: 'Spectral Guard',
    description: 'Raise a vengeful guard that reflects a share of incoming damage back at attackers.',
    icon: '/game/skills/skill-icon-holy-shield.png', cat: 'aura', kind: 'utility',
    manaCost: 45, castMs: 0, cooldownMs: 35000, levelRequired: 40, isBlocking: false,
    selfTarget: true,
    role: 'tank', school: 'shadow', scalingStat: 'con', targetMode: 'self', pveUse: ['sustain', 'boss'],
    effects: [{ type: 'damageReflect', value: 35, durationMs: 8000 }],
  },
  rebirth: {
    id: 'rebirth', name: 'Rebirth',
    description: 'A massive shield that briefly makes the caster nearly invulnerable.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'instant', kind: 'utility',
    manaCost: 80, castMs: 1000, cooldownMs: 120000, levelRequired: 40,
    effects: [{ type: 'shield', value: 800, durationMs: 8000 }],
  },
  sacred_aura: {
    id: 'sacred_aura', name: 'Sacred Aura',
    description: 'A constant pulse of healing to nearby allies.',
    icon: '/game/skills/skill_holyLight.svg', cat: 'aura', kind: 'utility',
    manaCost: 70, castMs: 1500, cooldownMs: 60000, area: 8, levelRequired: 40,
    effects: [{ type: 'heal', value: 200 }],
  },
  treasure_sense: {
    id: 'treasure_sense', name: 'Treasure Sense',
    description: 'Reveals loot drops at a glance.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'utility',
    manaCost: 20, castMs: 0, cooldownMs: 60000, levelRequired: 40, isBlocking: false,
    // B8 — actually reveals ground loot (was an unrelated evasion buff).
    effects: [{ type: 'reveal_loot', value: 1, durationMs: 30000 }],
  },
  stalking_arrow: {
    id: 'stalking_arrow', name: 'Stalking Arrow',
    description: 'A relentless arrow that slows the target.',
    icon: '/game/skills/skill_melee.svg', cat: 'projectile', kind: 'physical',
    manaCost: 40, castMs: 700, cooldownMs: 12000, dmg: 320, range: 26,
    levelRequired: 40, requiresTarget: true,
    effects: [{ type: 'damage', value: 320 }, { type: 'slow', value: 40, durationMs: 5000 }],
  },
  rift_step: {
    id: 'rift_step', name: 'Rift Step',
    description: 'Step through the target and rupture a small rift, cutting and slowing nearby enemies.',
    icon: '/game/skills/skill-icon-shadow-strike.png', cat: 'instant', kind: 'physical',
    damageElement: 'shadow',
    manaCost: 38, castMs: 0, cooldownMs: 18000, dmg: 190, range: 14, area: 3,
    levelRequired: 40, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'shadow', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'pack', 'escape'],
    shape: { kind: 'circle', radius: 3, anchor: 'target' },
    affects: 'enemies',
    blink: { offset: 1.4 },
    effects: [{ type: 'damage', value: 190 }, { type: 'slow', value: 35, durationMs: 3500 }],
  },
  rewind_mark: {
    id: 'rewind_mark', name: 'Rewind Mark',
    description: 'Snap back to your recent position and recover part of missing HP and MP.',
    icon: '/game/skills/skill-icon-arcane-supremacy.png', cat: 'instant', kind: 'utility',
    manaCost: 45, castMs: 0, cooldownMs: 45000, levelRequired: 20, isBlocking: false, selfTarget: true,
    role: 'mobility', school: 'arcane', scalingStat: 'wit', targetMode: 'self', pveUse: ['escape', 'sustain'],
    customBehavior: 'rewindMark',
    effects: [],
  },
  portal_pair: {
    id: 'portal_pair', name: 'Portal Pair',
    description: 'Open linked gates, relocating nearby allies to the target point while preserving formation.',
    icon: '/game/skills/skill-icon-group-bless.png', cat: 'aura', kind: 'utility',
    manaCost: 60, castMs: 400, cooldownMs: 40000, range: 22, area: 4.5, levelRequired: 40,
    role: 'mobility', school: 'arcane', scalingStat: 'wit', targetMode: 'ground', pveUse: ['escape', 'opener'],
    customBehavior: 'portalPair',
    effects: [],
  },
  gravity_well: {
    id: 'gravity_well', name: 'Gravity Well',
    description: 'Collapse space around a target, pulling nearby enemies inward and slowing them.',
    icon: '/game/skills/skill-icon-arcane-supremacy.png', cat: 'aura', kind: 'magical',
    manaCost: 70, castMs: 800, cooldownMs: 30000, range: 22, area: 7, levelRequired: 40, requiresTarget: true,
    role: 'control', school: 'arcane', scalingStat: 'int', targetMode: 'enemy', pveUse: ['pack', 'opener'],
    customBehavior: 'gravityWell',
    effects: [],
  },
  mirror_spell: {
    id: 'mirror_spell', name: 'Mirror Spell',
    description: 'Ready a mirror ward that copies a portion of the next magical hit back at the attacker.',
    icon: '/game/skills/skill-icon-holy-shield.png', cat: 'instant', kind: 'utility',
    manaCost: 45, castMs: 0, cooldownMs: 32000, levelRequired: 20, isBlocking: false, selfTarget: true,
    role: 'utility', school: 'arcane', scalingStat: 'wit', targetMode: 'self', pveUse: ['sustain', 'boss'],
    customBehavior: 'mirrorSpell',
    effects: [],
  },
  soul_link: {
    id: 'soul_link', name: 'Soul Link',
    description: 'Bind two nearby enemies so damage to either echoes into the other.',
    icon: '/game/skills/skill-icon-soul-eater.png', cat: 'instant', kind: 'magical',
    manaCost: 50, castMs: 500, cooldownMs: 24000, range: 18, levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'shadow', scalingStat: 'men', targetMode: 'enemy', pveUse: ['pack', 'boss'],
    customBehavior: 'soulLink',
    effects: [],
  },
  phase_step: {
    id: 'phase_step', name: 'Phase Step',
    description: 'Slip through the target, leave a brief afterimage, and strike from the far side.',
    icon: '/game/skills/skill-icon-shadow-strike.png', cat: 'instant', kind: 'physical',
    manaCost: 35, castMs: 0, cooldownMs: 16000, range: 14, levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'shadow', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'escape'],
    customBehavior: 'phaseStep',
    effects: [],
  },
  projectile_capture: {
    id: 'projectile_capture', name: 'Projectile Capture',
    description: 'Orbiting wards catch the next projectile and send part of its force back.',
    icon: '/game/skills/skill-icon-holy-shield.png', cat: 'instant', kind: 'utility',
    manaCost: 45, castMs: 0, cooldownMs: 30000, levelRequired: 20, isBlocking: false, selfTarget: true,
    role: 'tank', school: 'arcane', scalingStat: 'wit', targetMode: 'self', pveUse: ['sustain', 'boss'],
    customBehavior: 'projectileCapture',
    effects: [],
  },
  terrain_sigil: {
    id: 'terrain_sigil', name: 'Terrain Sigil',
    description: 'Etch a binding rune under the target area, damaging and rooting enemies caught inside.',
    icon: '/game/skills/skill-icon-group-bless.png', cat: 'aura', kind: 'utility',
    manaCost: 55, castMs: 600, cooldownMs: 26000, range: 18, area: 5, levelRequired: 40, requiresTarget: true,
    role: 'control', school: 'nature', scalingStat: 'wit', targetMode: 'enemy', pveUse: ['pack', 'opener'],
    customBehavior: 'terrainSigil',
    effects: [],
  },
  puppet_mastery: {
    id: 'puppet_mastery', name: 'Puppet Mastery',
    description: 'Hijack a creature briefly, breaking its target focus and suppressing its aggression.',
    icon: '/game/skills/skill-icon-soul-eater.png', cat: 'instant', kind: 'magical',
    manaCost: 50, castMs: 700, cooldownMs: 28000, range: 16, levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'shadow', scalingStat: 'men', targetMode: 'enemy', pveUse: ['single-target', 'escape'],
    customBehavior: 'puppetMastery',
    effects: [],
  },
  momentum_strike: {
    id: 'momentum_strike', name: 'Momentum Strike',
    description: 'Convert movement speed into impact damage and a heavy knockback.',
    icon: '/game/skills/skill_melee.svg', cat: 'instant', kind: 'physical',
    manaCost: 35, castMs: 0, cooldownMs: 14000, range: 5, levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'damage', school: 'physical', scalingStat: 'str', targetMode: 'enemy', pveUse: ['opener', 'single-target'],
    customBehavior: 'momentumStrike',
    effects: [],
  },
  delayed_fate: {
    id: 'delayed_fate', name: 'Delayed Fate',
    description: 'Mark a target with fate debt that detonates a moment later.',
    icon: '/game/skills/skill-icon-arcane-supremacy.png', cat: 'instant', kind: 'magical',
    manaCost: 45, castMs: 400, cooldownMs: 22000, range: 20, levelRequired: 20, requiresTarget: true,
    role: 'damage', school: 'arcane', scalingStat: 'int', targetMode: 'enemy', pveUse: ['boss', 'single-target'],
    customBehavior: 'delayedFate',
    effects: [],
  },
  clone_swap: {
    id: 'clone_swap', name: 'Clone Swap',
    description: 'Leave an illusion at your old position, then swap pressure to the far side of the target.',
    icon: '/game/skills/skill-icon-shadow-strike.png', cat: 'instant', kind: 'physical',
    manaCost: 40, castMs: 0, cooldownMs: 24000, range: 14, levelRequired: 20, requiresTarget: true, isBlocking: false,
    role: 'mobility', school: 'shadow', scalingStat: 'dex', targetMode: 'enemy', pveUse: ['opener', 'escape'],
    customBehavior: 'cloneSwap',
    effects: [],
  },
  silence_bubble: {
    id: 'silence_bubble', name: 'Silence Bubble',
    description: 'Create a quiet field that prevents enemy casts without stopping movement.',
    icon: '/game/skills/skill-icon-group-bless.png', cat: 'aura', kind: 'utility',
    manaCost: 55, castMs: 400, cooldownMs: 28000, range: 18, area: 6, levelRequired: 20, requiresTarget: true,
    role: 'control', school: 'holy', scalingStat: 'men', targetMode: 'enemy', pveUse: ['pack', 'boss'],
    shape: { kind: 'circle', radius: 6, anchor: 'target' },
    affects: 'enemies',
    effects: [{ type: 'silence', value: 1, durationMs: 4000 }],
  },
  reflection_contract: {
    id: 'reflection_contract', name: 'Reflection Contract',
    description: 'Bind incoming harm into a harsher retaliation contract for a short window.',
    icon: '/game/skills/skill-icon-holy-shield.png', cat: 'instant', kind: 'utility',
    manaCost: 50, castMs: 0, cooldownMs: 42000, levelRequired: 20, isBlocking: false, selfTarget: true,
    role: 'tank', school: 'shadow', scalingStat: 'con', targetMode: 'self', pveUse: ['sustain', 'boss'],
    effects: [{ type: 'damageReflect', value: 70, durationMs: 5000 }],
  },
  cataclysm_rings: {
    id: 'cataclysm_rings', name: 'Cataclysm Rings',
    description: 'Telegraph a boss-style ring blast: the center is safe, the outer ring burns.',
    icon: '/game/skills/skill_fireball.png', cat: 'aura', kind: 'magical',
    damageElement: 'fire',
    manaCost: 85, castMs: 0, cooldownMs: 50000, dmg: 420, range: 22, area: 8, levelRequired: 40, requiresTarget: true, isBlocking: false,
    role: 'damage', school: 'fire', scalingStat: 'int', targetMode: 'enemy', pveUse: ['pack', 'boss'],
    shape: { kind: 'donut', innerRadius: 3, outerRadius: 8, anchor: 'target' },
    affects: 'enemies',
    telegraph: { windUpMs: 1600 },
    effects: [{ type: 'damage', value: 420 }, { type: 'burn', value: 5, durationMs: 6000 }],
  },
};
