/**
 * §49/M1+ — content audit CLI.
 *
 * Walks the content registries and writes `docs/UNLINKED.md` with
 * every dangling reference the *soft* validators surface: items
 * with no use, skills nothing references, mini-bosses no quest
 * targets, etc.
 *
 * Why a separate doc rather than ROADMAP entries: the roadmap is
 * curated narrative; the unlinked list is a derived snapshot. Auto-
 * mutating the roadmap risks clobbering hand-written reconciliation
 * notes (§46, §48). Tracking the snapshot in `docs/UNLINKED.md`
 * keeps the audit in git history and out of the human roadmap.
 *
 * Usage:
 *   pnpm run content:audit          # regenerate the snapshot
 *   pnpm run content:audit --check  # exit non-zero if stale
 *
 * The `--check` mode is what `pnpm run check` calls — it asserts
 * that the dev ran `content:audit` after any content change that
 * affected the unlinked set.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ITEMS } from '../packages/content/items.js';
import { MINI_BOSSES } from '../packages/content/miniBosses.js';
import { SKILLS } from '../packages/content/skills.js';
import {
  findUnquestedBosses,
  findUnreachableSkills,
  findUnsourcedItems,
  findUnusedItems,
} from '../packages/content/obtainability.js';

const REPO_ROOT = process.cwd();
const SNAPSHOT_PATH = join(REPO_ROOT, 'docs', 'UNLINKED.md');

const isCheck = process.argv.includes('--check');

const unusedItems = findUnusedItems();
const unsourcedItems = findUnsourcedItems();
const unreachableSkills = await findUnreachableSkills();
const unquestedBosses = findUnquestedBosses();

function line(itemId: string, name?: string): string {
  return name && name !== itemId ? `- [ ] \`${itemId}\` — ${name}` : `- [ ] \`${itemId}\``;
}

const lines: string[] = [];
lines.push('# Unlinked Content Snapshot');
lines.push('');
lines.push('Auto-generated by `pnpm run content:audit`. Do not edit by hand.');
lines.push('');
lines.push('Every entry here is a real item / skill / boss the engine knows about but nothing in the world *uses*. Adding a use → run the audit script → this entry disappears. The roadmap entry it implies is recorded as an unchecked `[ ]` line so a future PR can come back to it.');
lines.push('');

lines.push('## Items with no source (hanging in the air)');
lines.push('');
lines.push('In `ITEMS` but nothing drops / sells / crafts / quest-rewards them. The wiki shows the item but the player has no way to obtain it. Whitelist members (`OBTAINABILITY_WHITELIST` in `packages/content/obtainability.ts`) are flagged with `(whitelisted)` — CI accepts them today but the gap is real and should be wired up.');
lines.push('');
if (unsourcedItems.length === 0) {
  lines.push('_None._');
} else {
  for (const entry of unsourcedItems) {
    const name = ITEMS[entry.id]?.name;
    const suffix = entry.whitelisted ? ' (whitelisted)' : '';
    lines.push(name && name !== entry.id
      ? `- [ ] \`${entry.id}\` — ${name}${suffix}`
      : `- [ ] \`${entry.id}\`${suffix}`);
  }
}
lines.push('');

lines.push('## Items with no use');
lines.push('');
lines.push('Has a source (loot/vendor/recipe/quest reward) but nothing consumes it: not a consumable, not equippable, not a recipe input, not currency.');
lines.push('');
if (unusedItems.length === 0) {
  lines.push('_None._');
} else {
  for (const id of unusedItems) lines.push(line(id, ITEMS[id]?.name));
}
lines.push('');

lines.push('## Skills nothing references');
lines.push('');
lines.push('Declared in `SKILLS` but not in any class skill tree, spec/proficiency skill list, or `UNIVERSAL_SKILLS`.');
lines.push('');
if (unreachableSkills.length === 0) {
  lines.push('_None._');
} else {
  for (const id of unreachableSkills) lines.push(line(id, SKILLS[id as keyof typeof SKILLS]?.name));
}
lines.push('');

lines.push('## Mini-bosses with no quest target');
lines.push('');
lines.push('Spawned in some zone but no quest objective asks the player to kill them.');
lines.push('');
if (unquestedBosses.length === 0) {
  lines.push('_None._');
} else {
  for (const id of unquestedBosses) lines.push(line(id, MINI_BOSSES[id]?.name));
}
lines.push('');

const generated = lines.join('\n');

if (isCheck) {
  let existing = '';
  try { existing = readFileSync(SNAPSHOT_PATH, 'utf8'); } catch { /* missing */ }
  if (existing !== generated) {
    console.error('docs/UNLINKED.md is out of date. Run `pnpm run content:audit` and commit the result.');
    process.exit(1);
  }
  console.log(`docs/UNLINKED.md is up to date (${unsourcedItems.length} hanging, ${unusedItems.length} unused, ${unreachableSkills.length} skill(s), ${unquestedBosses.length} boss(es) unlinked).`);
  process.exit(0);
}

writeFileSync(SNAPSHOT_PATH, generated);
console.log(`Wrote ${SNAPSHOT_PATH}`);
console.log(`  hanging=${unsourcedItems.length}  unused=${unusedItems.length}  skills=${unreachableSkills.length}  bosses=${unquestedBosses.length}`);
